version: 2.1

commands:
  install_dependencies:
    steps:
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package-lock.json" }}-{{ .BuildNum }}
      - run:
          name: Install local dependencies
          command: npm install

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.9-browsers
    steps:
      - checkout
      - run:
          name: Show the current branch
          command: echo ${CIRCLE_BRANCH}
      - install_dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ .BuildNum }}
          paths:
            - ./node_modules
      - run:
          name: Check ng
          command: npx ng version
  test:
    working_director: ~/app
    docker:
      - image: circleci/node:10.9-browsers
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build