version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
        name: Show the current branch
        command: echo ${CIRCLE_BRANCH}
      - run:
        name: Install local dependencies
        command: npm install
      - run:
        name: Linting
        command: npm run lint
      - run:
        name: Testing
        command: npm run test
        