version: 2.1

executors:
  default_executor:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.9-browsers

commands:
  install_dependencies:
    steps:
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package-lock.json" }}-{{ .BuildNum }}
      - run:
          name: Install local dependencies
          command: npm install

jobs:
  build:
    executor:
      name: default_executor
    steps:
      - checkout
      - run:
          name: Show the current branch
          command: echo ${CIRCLE_BRANCH}
      - install_dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ .BuildNum }}
          paths:
            - ./node_modules
      - run:
          name: Check ng
          command: npx ng version
  test:
    executor:
      name: default_executor
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
  deploy:
    executor:
      name: default_executor
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build production
          command: npx ng build --prod --aot
      - add_ssh_keys:
          fingerprints:
            - "ed:58:5d:5e:61:e4:8a:f5:42:f6:94:d8:68:46:39:59"
      - run:
          name: Deploy production build
          command: |
            mkdir deploy && cd deploy
            git config --global user.email "jp01r7@gmail.com"
            git config --global user.name "jp6rt"
            git init && git remote add origin ${remote}
            git pull origin master
            rm -rf * && mv ../dist/portfolio/* ./
            git add -A && git commit -m "Build {{ checksum "package-lock.json" }}-{{ .BuildNum }}"            
            git push origin master

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test